# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WXrrsFO0ytKFzNy6PBRigYp7TqRdKTWP
"""

import pandas as pd
df = pd.read_csv("summer_olympic.csv")
df

"""**# 1. In how many cities Summer Olympics is held so far?**"""

len(df['City'].unique())
# print("Name of Cities are : \n")
# li = df['City'].unique()
# for item in li:
#   print(item)

"""**#2. Which sport is having most number of Gold Medals so far?(Top 5)**"""

data = df[df['Medal']=='Gold']
data.groupby(['Sport','Medal'])
li = []
for sport in data['Sport'].unique():
    li.append([sport,len(data[data['Sport']==sport])])
li = pd.DataFrame(li, columns = ['Sport','Gold'])
li.sort_values(by = 'Gold', ascending = False).head().plot(x = 'Sport', y = 'Gold', kind = 'bar', figsize = (15,5))

"""**# 3. Which sport is having most number of medals so far? (Top 5)**"""

data = df
data.groupby(['Sport','Medal'])
li = []
for sport in data['Sport'].unique():
    li.append([sport,len(data[data['Sport']==sport])])
li = pd.DataFrame(li,columns = ['Sport','Medal']).sort_values(by = 'Medal', ascending = False)
li.head().plot(x = 'Sport', y = 'Medal', kind = 'bar', figsize = (15,5))

"""**# 4. Which player has won most number of medals? (Top 5)**"""

data = df
data.groupby(['Athlete','Medal'])
li = []
for athlete in data['Athlete'].unique():
    li.append([athlete, len(data[data['Athlete']==athlete])])
li = pd.DataFrame(li, columns=['Athlete','Medal_count']).sort_values(by = 'Medal_count',ascending = False)
li.head().plot(x = 'Athlete', y = 'Medal_count', kind = 'bar',figsize = (15,5))

"""**# 5. Which player has won most number Gold Medals of medals? (Top 5)"**"""

data = df
data = data[data['Medal']=='Gold']
li = []
for player in data['Athlete'].unique():
    li.append([player, len(data[data['Athlete']==player])])
li = pd.DataFrame(li, columns=['Player','Gold'])
li = li.sort_values(by = 'Gold',ascending=False)
li.head().plot(x = 'Player', y = 'Gold', kind = 'bar', figsize=(15,5))

"""**# 6. In which year India won first Gold Medal in Summer Olympics?"**"""

data = df
data = data[data['Country']=='IND']
data = data[data['Medal']=='Gold']
data.sort_values(by = 'Year')
ans = pd.DataFrame(data['Year'].head(1),columns=['Year'])
ans

"""**# 7. Which event is most popular in terms on number of players? (Top 5)**"""

data = df
li = []
for num in data['Event'].unique():
    li.append([num, len(data[data['Event']==num])])
li = pd.DataFrame(li,columns=['Event','Num_of_Player']).sort_values(by = 'Num_of_Player',ascending= False)
li.head().plot(x = 'Event', y = 'Num_of_Player', kind = 'bar', figsize=(15,5))

"""**# 8. Which sport is having most female Gold Medalists? (Top 5)**"""

data = df
data = data[data['Medal']=='Gold']
data = data[data['Gender']=='Women']
li = []
for sport in data['Sport'].unique():
    li.append([sport,len(data[data['Sport']==sport])])
data = pd.DataFrame(li,columns=['Sport','No_of_women'])
data = data.sort_values(by = 'No_of_women',ascending=False)
data.head().plot(x = 'Sport', y = 'No_of_women', kind = 'bar', figsize=(15,5))